---

- name: First PB
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

  - name: Get config of IOS devices
    ios_facts:
      gather_subset: all

  - name: Display the config
    debug:
       - msg: "{{ansible_net_hostname}}"
